openapi: 3.0.0
info:
  title: AAA api specs
  version: 1.0.0
  description: 
    $ref: index.md
    

tags:
  - name: Image
    description: Operations about images.
paths:
  /images:
    $ref: paths/images.yaml
  /images/{id}:
    $ref: ./paths/images_{id}.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:images: read users info
            write:images: modify or add images
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
